### ISSUE TITLE
Scale image to device size

### ISSUE THREAD

**Issue by wildeKaiserin** [mobileappdevhm19/HINT-Reader#27]
Everytime we open, switch / change orientation or split our screen to another size, we have to rescale the image to adapt on the device size.

**Comment by ghost** [comment]
fyi: mediaQueries seem to report the width and height in points.
e.g. i get h896.0 w414 for a triple retina display of h2688 w1242

**Comment by ghost** [comment]
As far as "Safe Areas" go, should we try to work out how to address the notch-shaped elephant in the room in sprint 1?
Because just going by screen resolution isn't enough for certain cases.

(ref.)
[https://cdn-images-1.medium.com/max/1000/1*XJro6ujERnKVXIcDVXy6kw.png](https://cdn-images-1.medium.com/max/1000/1*XJro6ujERnKVXIcDVXy6kw.png)
[https://cdn-images-1.medium.com/max/800/1*rwWMirhEosAfaBnkWOwBpg.png](https://cdn-images-1.medium.com/max/800/1*rwWMirhEosAfaBnkWOwBpg.png)

What do you think?

**Comment by maxiking203** [comment]
Is covered by feature devicesize branch
