### ISSUE TITLE
Filling the Bookshelf programmatically

### ISSUE THREAD

**Issue by wildeKaiserin** [mobileappdevhm19/HINT-Reader#35]
Right now, the bookshelf is static, the bookshelf should adapt to the list of books in storage. We probably need a database to save the state of our bookshelf.

**Comment by maxiking203** [comment]
Let us know if you need help here!

**Comment by GiorgioBullo** [comment]
Now I'm working on a dataset, when it will be completed, the new scrollable view list for the bookshield can use the informations from the dataset to create automatic scroll views.

**Comment by GiorgioBullo** [comment]
In the previous message dataset=database...

The database is completed. Now it checks a json file from the folder asset and it takes the books from there.
The json file is supposed to be created by the backend, or, in a future release, by us. So far, there is a symbolic 'books.json' file with 5 books.
In the BookShelfView there is an example of how to use the database, so with that and the class BookCard, the issue #33 has all the elements to be completed. I also created 2 buttons with which it's possible to add or delete a book to/from the database. The purposes of these 2 buttons are debugging and prototyping, so even if now we cannot add physical books, we can add fake books to fill the book shelf view.

In the file database.dart the function deleteAll() doesn't work, because I don't know the correct syntax for rawDelete(...). Please, if you know it, correct it.

**Comment by ghost** [comment]
scrolling bookshelves have been added to the develop branch (BookshelfView.dart). you might want to incorporate them into your branch, so you don't get merge conflicts later.

**Comment by maxiking203** [comment]
The branch is missing the book.json File. I can't run the app without that.

**Comment by maxiking203** [comment]
Nice that we can load some "real" testdata in the BookShelfView and also can add and delete "books" there.
The database branch which was used for the feature is still open for improvment. The current feature is merged into and test were added.
