### ISSUE TITLE
Slides Presentation for Sprint 2

### ISSUE THREAD

**Issue by wildeKaiserin** [mobileappdevhm19/HINT-Reader#42]
Google Slides Presentation for Sprint 2

**Comment by ghost** [comment]
I'll gladly take care of that one.

**Comment by ghost** [comment]
Feel free to review :)

https://docs.google.com/presentation/d/1CHPZh-70qSSiNO3n4hLMs6kgLKppI9jXwxid-2HTnLY/edit?usp=sharing

**Comment by GiorgioBullo** [comment]
I like the slide format :D and I can gladly say that we can set the feature "Most recently opened books in the first row of the CollectionView" as done!

The slides 2-3-4 are little empty, maybe we could add:
-in slide 2 a screen of the bookshelfview as it was during the sprint1 (if we have it),
-in slide 3 the link to the repository,
-in slide 4 a screen of the actual bookshelfview.
But maybe it's not harmonious as I say.

**Comment by ghost** [comment]
Another green checkmark then :)

I would personally advise against putting screenshots in the title card slides, because I do not expect to spend more than 5 seconds per slide for these. It's just titles, in my mind at least

how about a screenshot from sprint 1 and after sprint 2 during the outlook?
if you could provide a screencap of your feature branch ...

**Comment by GiorgioBullo** [comment]
sent the screen to you :D

**Comment by ghost** [comment]
added a new final slide with paper prototype, sprint 1, and sprint 2 for the bookshelfview to see the progress we made
i'd be happy with the slides as they are, if there are no more ideas, i'll close the issue tomorrow

**Comment by wildeKaiserin** [comment]
Slides are ready for presentation!
