### ISSUE TITLE
Sonarcloud/Sonarqube for flutter

### ISSUE THREAD

**Issue by gsocher** [mobileappdevhm19/HINT-Reader#52]
as far as I know, Sonarqube/Sonarcloud does not support flutter. Do you still need access to it from your github repo?

see [https://stackoverflow.com/questions/53520081/is-there-any-code-inpector-like-sonarqube-for-flutter](https://stackoverflow.com/questions/53520081/is-there-any-code-inpector-like-sonarqube-for-flutter)

**Comment by DManstrator** [comment]
Dear Professor Socher,

thank you for your response. I already expected this to be honest but I wanted to try it out just in case since I liked using it in Software Engineering back then and I thought it was good for covering the "Code Analysis" part in the final presentation.

Since it seems that this won't work, I don't see a reason to give it access to our repository, instead I will try out the suggested answers (`flutter analyze`).

Kind regards,

Daniel Gabl

**Comment by DManstrator** [comment]
I've added Static Code Analysis to the project which gives advanced warning while programming and it will also be covered in the presentation, thanks for providing that link.
